### ISSUE TITLE
nsched

### ISSUE THREAD

**Issue by irbees2008** [vponomarev/ngcms-plugins#12]
не работает , на последнем релизе, публикует сразу

**Comment by stdex** [comment]
Смотря как использовать. Очевидно, что при добавлении нужно выбирать "Отправить на модерацию".

**Comment by irbees2008** [comment]
все равно не публикует, php7. двиг последний

**Comment by stdex** [comment]
Параметры cron задачи какие?

**Comment by irbees2008** [comment]
5 минут  на одном сайте, на другом без крона

**Comment by irbees2008** [comment]
перезалил, установил, с кроном работает, без крона несработало

**Comment by stdex** [comment]
Псевдо cron задача создается, в момент настройки плагина. Поэтому стандартно задача создается.

**Comment by irbees2008** [comment]
Зашел на страницу с плагинами , плагин включён, прохожу в планировщик там в таблице нет действия от плагина. Захожу в настройки плагина, но ничего там нетрогаю перехожу в планировщик  появилась задача. Все заработало.
Т.е. надо обязательно зайти в настройки плагина чтобы появилась запись в кроне

**Comment by irbees2008** [comment]
Не работает он нормально, походу глючит, то публикует то нет
