### ISSUE TITLE
Плагины

### ISSUE THREAD

**Issue by irbees2008** [vponomarev/ngcms-plugins#22]
Надо удалить из ветки устаревшие и дублирующие плагины

**Comment by vponomarev** [comment]
Закончим с админкой - займусь расчисткой плагинов.
Первым делом переключу ветку UTF8 на основную, а потом методично будем проверять работоспособность.

Также планирую часть совсем нужных плагинов (типа auth_basic) перенести в основной репозиторий, тогда двиг можно будет полноценно установить из одного репозитория, а не из двух (как сейчас).

**Comment by russsiq** [comment]
Давайте переоткроем эту ветку и в ней (помимо форума на сайте) как-то решим какие плагины нужно оставить, ну и приоритетность?

**Comment by vponomarev** [comment]
Давай.

Навскидку список получается такой (без уточнения что работает, а что нет), в файл version добавим параметр "минимальная совместимая версия движка" и по нему будем фильтровать плагины в админке:
- нулевой приоритет (must be):
auth_basic
uprofile
- очень нужны
archive
calendar
comments
lastnews
lastcomments
xfields
switcher
- полезны
ads
ads_pro
auth_social
bookmarks
breadcrumbs
complain
favorites
feedback
filter
forum
gmanager
pm
nsched

- отдельно с не до конца понятным статусом, скорее для интернет-магазинов:
finance
basket

Но основной вопрос будет по ресурсам - нужно будет перепроверять всё.
А с учётом отсутствия версии с давних времён - сразу после готовности админки нужно будет набрать минимально необходимый набор плагинов и выпускать по ним релиз.

**Comment by russsiq** [comment]
Если особо не разворачиваться и учесть опыт создания пары сайтов на NGCMS:
- `auth_basic` – можно сказать, что он как часть ядра;
- `breadcrumbs`;
- `feedback`;
- `gsmg`;
- `rss_export`;
- `tags`;
- `xfields`;
- `xnews`.

Эти плагины я бы просмотрел, адаптировал бы под новую админку.

Все остальные плагины:
- спорные (`gmanager`, `pm`);
- неподъемные для быстрого просмотра и проверки кода (`forum`);
- дублирующиеся (`lastnews`, `favorites` дублируют `xnews`);
- с непонятным функционалом (`ads...`);
- не приоритетные (`comments`, `lastcomments`, `subscribe_comments`,  `voting`).

----

Очень нужна небольшая функция для очистки директории кэша из админки.

**Comment by irbees2008** [comment]
ads устаревший, замена ads pro
gmanager нужен, мне это точно для переезда

**Comment by irbees2008** [comment]
Вот кеш это да ,тоже надо

**Comment by vponomarev** [comment]
> Очень нужна небольшая функция для очистки директории кэша из админки.

Взято в работу

**Comment by vponomarev** [comment]
> Очень нужна небольшая функция для очистки директории кэша из админки.

Готово, проверяйте :)

**Comment by russsiq** [comment]
> Готово, проверяйте :)

Работает. Только при одном нажатии на очистку отправляются два запроса: на очистку и на получение размера. Может сделать, чтобы сразу возвращался подсчет?

**Comment by russsiq** [comment]
Хотя не принципиально и так сойдет )

**Comment by vponomarev** [comment]
> Только при одном нажатии на очистку отправляются два запроса: на очистку и на получение размера.
> Может сделать, чтобы сразу возвращался подсчет

Специально так оставил.
Лишний HTTP запрос почти ничего не стоит, зато нет дублирования кода и проще серверная часть.

Кстати, как будет время - подшамань обновлённый модуль личных сообщений.
Там при написании письма/ответа я не нашёл как вставить правильные стили и From/To/Subject стоит просто текстом.

**Comment by russsiq** [comment]
Так сойдет?

![Снимок](https://user-images.githubusercontent.com/11920039/87864685-c54ef500-c9ae-11ea-9050-33fdc024a8a9.PNG)

**Comment by vponomarev** [comment]
> Так сойдет?

Да, отлично.
