### ISSUE TITLE
xfields не учитывает порядок вывода доп. полей согласно сортировке в Новости: группы

### ISSUE THREAD

**Issue by morethanwords-agency** [vponomarev/ngcms-plugins#6]
Если создать группу полей и отсортировать их в нужном порядке в "Новости: группы" то при создании/редактировании новости доп. поля выводятся согласно сортировке **в общем списке** (Новости: поля)

**Comment by vponomarev** [comment]
Такая проблема есть, но решения сейчас нет.
При выборе категории JScript определяет какие именно поля из XFields отображать, а какие - нет.
Т.е. управление на уровне visible / no visible.

Для изменения порядка необходимо будет пересоздавать строки, что скорее всего приведёт к потере уже заполненных данных из полей. Если известно альтернативное решение без потери данных - пиши, попробуем реализовать его
