### ISSUE TITLE
feedback 0.26

### ISSUE THREAD

**Issue by morethanwords-agency** [vponomarev/ngcms-plugins#9]
При использовании шаблонов в `/custom/<tplname>/*` вываливается ошибка 
`Unable to find template "site.notify.tpl" (looked into: /Applications/MAMP/htdocs/<sitename>/www/templates/<tplname>, /Applications/MAMP/htdocs/<sitename>/www/engine).`

**Comment by ROZARD** [comment]
Не подтверждено.
Необходимо проверить пути
/templates/<имя шаблона сайта>/plugins/feedback/custom/<имя шаблона плагина>/{шаблоны}
